title: "Institut CAR Sant Cugat"

markdown: kramdown

theme_note: "test"

collections:
  activitat:
    output: true
    permalink: /vida/activitat/:name.html

defaults:
  - scope:
      path: ""
      type: "activitat"
    values:
      layout: "activitat"