title: "Institut CAR Sant Cugat"

markdown: kramdown

collections:
  activitats:
    output: true
    permalink: /vida/activitats/:name.html

defaults:
  - scope:
      path: ""
      type: "activitats"
    values:
      layout: "activitat"